export const wtLearns = [
	{
		title: 'JavaScript',
		comment: 'it`s a base.',
		src: 'js.svg',
		rating: 5,
	},
	{
		title: 'HTML5',
		comment: 'it`s a base.',
		src: 'html5.svg',
		rating: 5,
	},
	{
		title: 'CSS',
		comment: 'it`s a base.',
		src: 'css.svg',
		rating: 5,
	},
	{
		title: 'ReactJS',
		comment: 'Интересная штука, которая меня радует :)',
		src: 'reactjs.svg',
		rating: 7,
	},
	{
		title: 'ViteJS',
		comment: 'Неизвестная штука, которая вроде интересна :)',
		src: 'vitejs.svg',
		rating: 3,
	},
	{
		title: 'NodeJS',
		comment: 'Великолепная штука, которая мне плохо известна :)',
		src: 'nodejs.svg',
		rating: 7,
	},
	{
		title: 'VueJS',
		comment: 'Интересная штука, конкурент штуки, которая радует',
		src: 'vuejs.svg',
		rating: 2,
	},
	{
		title: 'NuxtJS',
		comment: 'Не знаю, что это такое, но вроде интересно :)',
		src: 'nuxtjs.svg',
		rating: 3,
	},
	{
		title: 'npm',
		comment: 'Прикол великолепной штуки :)',
		src: 'npm.svg',
		rating: 4,
	},
	{
		title: 'Babel',
		comment: 'То ли сборщик, то ли разборщик, хз :)',
		src: 'babel.svg',
		rating: 4,
	},
	{
		title: 'Git',
		comment: 'it`s a base.',
		src: 'git.svg',
		rating: 7,
	},
	{
		title: 'GitHub',
		comment: 'it`s a base for base.',
		src: 'github.svg',
		rating: 7,
	},
	{
		title: 'VS code',
		comment: 'Даааа это код!!!',
		src: 'vs.svg',
		rating: 7,
	},
	{
		title: 'TypeScript',
		comment: 'Нужен для работы на крупных проектах?? Наверн ;)',
		src: 'typescript.svg',
		rating: 5,
	},
	{
		title: 'Sass',
		comment: 'Ваще хз, что это, но вроде мощный CSS',
		src: 'sass.svg',
		rating: 1,
	},
	{
		title: 'PostgreSQL',
		comment: 'Слоникам лайк, жаль, что PHP disлайк ;)',
		src: 'postgresql.svg',
		rating: 6,
	},
	{
		title: 'MySQL',
		comment: 'Вроде база, хз :)',
		src: 'mysql.svg',
		rating: 3,
	},
	{
		title: 'MongoDB',
		comment: 'Часто слышал, не знаю нужно ли...',
		src: 'mongodb.svg',
		rating: 1,
	},
	{
		title: 'Linux',
		comment: 'Бесплатная OC для серверов, юху!',
		src: 'linux.svg',
		rating: 3,
	},
	{
		title: 'Json',
		comment: '=/',
		src: 'json.svg',
		rating: 5,
	},
	{
		title: 'Docker',
		comment: 'Что-то архиважное 0_0',
		src: 'docker.svg',
		rating: 6,
	},
	{
		title: 'Chrome Dev',
		comment: 'Крутая штука, помогает часто!',
		src: 'chrome.svg',
		rating: 7,
	},
	{
		title: 'Figma',
		comment: 'Задизайнить только так!',
		src: 'figma.svg',
		rating: 5,
	},
	{
		title: 'WebPack',
		comment: 'ViteJS, но круче, но медленнее :(',
		src: 'webpack.svg',
		rating: 5,
	},
]